// Copyright 2023 The Cockroach Authors.
//
// Use of this software is governed by the CockroachDB Software License
// included in the /LICENSE file.

package mmaprototype

import (
	"time"

	"github.com/cockroachdb/cockroach/pkg/roachpb"
)

// Incoming messages for updating cluster state.

// StoreLoadMsg is periodically sent by each store. Load and Capacity are in
// physical units (e.g. CPU ns/s accounting for indirect overhead, physical disk
// bytes used/available). The integration layer converts raw metrics to physical
// quantities before constructing this message.
//
// For CPU, Load[CPURate] is the direct per-store replica CPU usage (unchanged),
// while Capacity[CPURate] is the physical CPU capacity available to this store
// (total node capacity minus background load, divided by the amplification
// factor and number of stores). The AmplificationFactor[CPURate] converts
// direct replica CPU to its total physical footprint.
//
// For disk, Load[ByteSize] is the physical disk bytes used by the store, and
// Capacity[ByteSize] is Used + Available. The AmplificationFactor[ByteSize]
// converts logical bytes (MVCC) to physical bytes.
type StoreLoadMsg struct {
	roachpb.NodeID
	roachpb.StoreID

	Load                LoadVector
	Capacity            LoadVector
	AmplificationFactor [NumLoadDimensions]float64
	SecondaryLoad       SecondaryLoadVector

	LoadTime time.Time
}

// StoreLeaseholderMsg is sent by a local store and includes information about
// all ranges for which this store is the leaseholder. The range information
// includes other replica stores. This is a local message and will be sent
// before every allocator pass, so that the allocator has the latest state to
// make decisions.
type StoreLeaseholderMsg struct {
	roachpb.StoreID

	// Ranges provides authoritative information from the leaseholder.
	Ranges []RangeMsg
}

// RangeMsg is generated by the leaseholder store (and part of
// StoreLeaseholderMsg). All fields except for MaybeSpanConf are always
// populated. The MaybeSpanConf is populated if there is a possible change in
// the SpanConfig (including when this is a new leaseholder for the range),
// and is indicated by MaybeSpanConfIsPopulated being true. The optional
// population is done to avoid the expensive processing of a SpanConfig by
// MMA, on every message for the range.
//
// The main reason we always populate Replicas is to ensure that the allocator
// does not lose synchronization with the current set of replicas, due to
// spurious changes (we had one undiagnosed example where the allocator was
// spuriously told that a lease was transferred away).
type RangeMsg struct {
	roachpb.RangeID
	Replicas                 []StoreIDAndReplicaState
	RangeLoad                RangeLoad
	MaybeSpanConfIsPopulated bool
	MaybeSpanConf            roachpb.SpanConfig
}
